import "./styles/globals.css";
import "./styles/mdx.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { PageHeader } from "@/components/page-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={cn(inter.className, "flex min-h-screen flex-col")}>
        <PageHeader />

        <main className="flex-1">{children}</main>

        <footer>teste</footer>
      </body>
    </html>
  );
}
